### ISSUE TITLE
Server orphaned in TF state causes broken workflow

### ISSUE THREAD

**Issue by TheAlpha0ne** [latitudesh/terraform-provider-latitudesh#14]
Server created by TF then deleted from the UI. Can't be deleted by TF because it throws a 404 on the DELETE call. 

 Error: DELETE https://api.maxihost.com/servers/22515: 404
│
│ Error
│ CODE: not_found
│ STATUS: 404
│ DETAIL: Specified Record Not Found

I believe we need to say if a server attempting to be deleted doesn't exist it than its deleted, then presume success for terraform.

WORKAROUND

terraform state rm  module.helium_server.module.server.latitude_server.server
Removed module.helium_server.module.server.latitude_server.server
Successfully removed 1 resource instance(s).
Releasing state lock. This may take a few moments...

**Comment by esoubihe** [comment]
Here's an idea, when we release instance tagging we could tag all instances created by TF and have the UI throw a notice that state will be lost. Wdyt?

**Comment by natebolam** [comment]
@esoubihe That sounds good - I'll add a tag like `tf-provisioned` to any resources created by the provider. Will handle it more gracefully on the backend as well.

**Comment by ljk662** [comment]
I believe this issue is fixed with the most recent PR #59

**Comment by ynhummel** [comment]
> I believe this issue is fixed with the most recent PR #59

You're right! this problem is solved from [v1.0.0-rc.3](https://github.com/latitudesh/terraform-provider-latitudesh/releases/tag/v1.0.0-rc.3) onwards.
