### ISSUE TITLE
Project data source NEEDED for server modules which implement project creation

### ISSUE THREAD

**Issue by TheAlpha0ne** [latitudesh/terraform-provider-latitudesh#15]
See another clouds ability to handle this  allows us to not to have a pre existing project in a shared server module genesis.

data "metal_project" "project" {
  name = local.project_name
}

local {
  create_project         = data.metal_project.project.id == null ? 1 : 0
}

resource "metal_project" "project" {
    count           = local.create_project
    name            = local.project_name
    organization_id = var.tsi.metal_org_id
  }

**Comment by natebolam** [comment]
WIP

**Comment by ynhummel** [comment]
I'll be closing this issue as it's been open for a long time, and we've made numerous updates to both the provider and the SDK since then. If this is still a problem, feel free to open another issue.
