### ISSUE TITLE
Add user_data/cloud-init support for deploying instances

### ISSUE THREAD

**Issue by mllnd** [latitudesh/terraform-provider-latitudesh#17]
We heavily rely on providing `cloud-init` configuration for deployed instances. Would be nice if there was an option to pass in the `user_data` while creating a new `latitude_server` resource.

Looking at the API documentation, I think the flow would be:

1. Add a new [User Data](https://docs.latitude.sh/reference/post-project-user-data)
2. Use the `id` value of new User Data and pass it with [create server](https://docs.latitude.sh/reference/create-server) request

**Comment by esoubihe** [comment]
@mllnd Markkus thank you for contributing. User data is now available on the terraform provider
