### ISSUE TITLE
Adding sites to the `latitudesh_plan` data source

### ISSUE THREAD

**Issue by anthonyra** [latitudesh/terraform-provider-latitudesh#37]
### Is your feature request related to a problem? Please describe.

It would be nice if the `latitudesh_plan` data source returned the sites that have that plan as available. That way the Terraform script is aware of available resources during planning.

### Describe the solution you'd like

After reviewing the source code I think it wouldn't be to unreasonable to collect the available sites in a list and pass it as a return. If this included `stock_level` it'd also help tremendously. I'm willing to attempt a PR if that'll help but wanted to see thoughts before putting in the time.
 
### Describe alternatives you've considered

Create a new data source that pulls up all plans and allows for all the available filters ['name', 'slug', 'location', 'stock_level', 'in_stock'] from the `get_plans` endpoint <https://docs.latitude.sh/reference/get-plans> ...

### Additional context

This would help when planning out clusters or seeing if 5 instances of a specific plan is available to be spun up.

**Comment by anthonyra** [comment]
It kind of aligns with the recent change to the dashboard where you pick an instance first than region. The instance type being the important thing, with my Terraform I rotate through all available sites for decentralization concerns. If I could get a list of regions with that instance available it'd help. If it returned the number of instances I could do some logic to ensure that I distribute my instances evenly across the regions/locations.

**Comment by ynhummel** [comment]
Now, with [v1.0.0](https://github.com/latitudesh/terraform-provider-latitudesh/releases/tag/v1.0.0), the `latitudesh_plan` datasource has an `in_stock` attribute with an array of sites where said plan is available, so I'll be closing this issue.

Unfortunately, due to the reasons stated above by @esoubihe we cant display numerical values for stock, only the slugs of the sites where there is stock available.
