### ISSUE TITLE
SSH Key not updated after key file content changes

### ISSUE THREAD

**Issue by RickDavis404** [latitudesh/terraform-provider-latitudesh#38]
# Bug Report

---

## Describe the bug

When you add a SSH key to a project using terraform, it does not update if that SSH key content changes.

### Affected Resource(s)

- latitudesh_ssh_key

### Expected Behavior

1. After applying, a `terraform plan` should not indicate a change is required when key name/contents have not changed.
2. After changing a SSH key contents, `terraform apply` should update the key contents within the Latitude.sh project/UI

### Actual Behavior

- Planning, re-applying doesn't properly check for key content changes. Key name changes are properly detected & updated, but not key content.
- Applying after changing key content does not update within the Latitude.sh project/web UI

### Steps to Reproduce

Steps to reproduce & debug logs available here... https://gist.github.com/RickDavis404/ec551f2dfb087d3eec5d387a212ef3cf#steps-to-reproduce

**Comment by esoubihe** [comment]
@RickDavis404 thank you for your contribution. I understand that you want to change the contents of an SSH Key after it's been created.

The API doesn't allow the content to be changed. Ref: https://docs.latitude.sh/reference/put-project-ssh-key. This is a security measure to avoid cases where bad actors might change a key.

Let me know if this answers your question or if I didn't understand the bug you're reporting.

**Comment by esoubihe** [comment]
I'm closing this as it seems this is an invalid request. Feel free to reopen it if you still think this is a bug. 

Thanks for your contribution!
