### ISSUE TITLE
 Cannot create servers with ssh_keys

### ISSUE THREAD

**Issue by zheli** [latitudesh/terraform-provider-latitudesh#46]
---
I couldn't create servers if I specified ssh_keys.

## Describe the bug

I got error
```
│ Inappropriate value for attribute "ssh_keys": a number is required.
```
If I assign a list of key ids to the server.

### Affected Resource(s)
- latitudesh_server

### Expected Behavior

Servers are created successfully.

### Actual Behavior

Servers are not created and terraform complains.

### Steps to Reproduce
1. Please try the following main.tf
````
resource "latitudesh_server" "server" {
  hostname         = "terraform.latitude.sh"
  operating_system = "ubuntu_22_04_x64_lts"
  plan             = "c3.small.x86"
  project          = latitudesh_project.project.id   
  site             = "DAL"
  ssh_keys         = ["{the ssh key id}"]
}
````
3. `terraform apply` 

**Terraform Configuration Files**

**Terraform version**

v1.4.6

**Debug Output**

**Panic Output**

## Additional context

**References**

**Comment by zheli** [comment]
I think it probably should use a different schema:
https://github.com/latitudesh/terraform-provider-latitudesh/blob/e56fc6615b276d3359258be8d6b8f89caeef6692/latitudesh/resource_server.go#L45C1-L52C6

**Comment by esoubihe** [comment]
Please see #45 for the suggested syntax and let me know if you're still having issues.

**Comment by ynhummel** [comment]
@zheli, we've rolled out some updates to improve the server's `ssh_keys` and `project` attributes. This should resolve the issue and https://github.com/latitudesh/terraform-provider-latitudesh/issues/45. Therefore, I'll be closing both of them.

Thank you for your feedback. If the problem persists or if you encounter any other issues, please feel free to contact us.
