### ISSUE TITLE
Server replacement should trigger rebuild if in the same region / instance class

### ISSUE THREAD

**Issue by magicniko** [latitudesh/terraform-provider-latitudesh#55]
### Is your feature request related to a problem? Please describe.

when capacity is low, it is clumsy to rebuild a server, e.g. if I change the terraform user data and want to rebuild a server, the deletion succeeds but if there is only one server of a given instance class in a region, the subsequent 'create' will fail. I have to poll the API to see when the instance class comes back online, and take it before someone else does. 

### Describe the solution you'd like

It would be better if the terraform provider called the `server reinstall` [api call](https://docs.latitude.sh/reference/create-server-reinstall) instead of delete->create, in cases where the region and instance class have not changed. 

### Describe alternatives you've considered

there is no alternative solution, other than polling the API to see when the capacity is available again, or to deploy in another region.

**Comment by ynhummel** [comment]
Hello @magicniko, you're right! We'll work to ensure that when rebuilding a server, reinstallation will be favored over recreation whenever possible.

Thank you for your suggestion!

**Comment by ynhummel** [comment]
Solved in the latest release https://github.com/latitudesh/terraform-provider-latitudesh/releases/tag/v1.0.0-rc.2 so I'll be closing this issue. Feel free to reach out if you have anything more to add!
