### ISSUE TITLE
Cannot save vlan assignment result into states

### ISSUE THREAD

**Issue by zheli** [latitudesh/terraform-provider-latitudesh#65]
---

## Describe the bug

When I try to assign a VLAN to the server, I got an error
```

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ latitudesh_vlan_assignment.vlan_assignments["ec5p-blockchain-signer-cosmos-mainnet-lem-1-3"],
│ provider "provider[\"registry.terraform.io/latitudesh/latitudesh\"]"
│ produced an unexpected new value: Root resource was present, but now
│ absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```
As a result, the state is not saved and terraform apply shows that I have unapplied changes. But I could see that the machine is assigned to the correct VLAN.

### Affected Resource(s)
- latitudesh_vlan_assignment

### Expected Behavior

`terraform apply` complete without errors.

### Actual Behavior

Terraform states are not saved.

### Steps to Reproduce

**Terraform Configuration Files**

```
resource "latitudesh_vlan_assignment" "vlan_assignment" {
    server_id          = "sv_R82A0yy6L06mM"
    virtual_network_id = "vlan_XDO7NYZvr5Pgw"
}
```
**Terraform version**

1.4.6

**Debug Output**

**Panic Output**

## Additional context

**References**

**Comment by ynhummel** [comment]
Thanks for reporting this error!

The latest update, [v1.1.1](https://github.com/latitudesh/terraform-provider-latitudesh/releases/tag/v1.1.1), addressed some issues that might have been causing this problem. It should not occur anymore, so I'll be closing this issue.
