### ISSUE TITLE
Cannot create tags using terraform

### ISSUE THREAD

**Issue by zheli** [latitudesh/terraform-provider-latitudesh#71]
---
Cannot create tags in a project

## Describe the bug

I tried to create a tag resource in my project using terraform but couldn't.

### Affected Resource(s)

latitudesh_tag
### Expected Behavior

Tag is created successfully.
### Actual Behavior

╷
│ Error: json: cannot unmarshal object into Go struct field TagTeam.data.attributes.team.currency of type string
│

### Steps to Reproduce

**Terraform Configuration Files**

**Terraform version**

❯ tg version
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v5.53.0
+ provider registry.terraform.io/latitudesh/latitudesh v1.1.1

**Debug Output**

**Panic Output**

## Additional context

**References**

**Comment by ynhummel** [comment]
Thank you for reporting this issue. I'll look into it!

**Comment by zheli** [comment]
> @zheli We've just updated the provider to [v1.1.2](https://github.com/latitudesh/terraform-provider-latitudesh/releases/tag/v1.1.2), which should fix this problem. Sorry if this caused you any inconvenience, and thank you for helping improve our provider!

Thanks @ynhummel !! I gonna try it out now.
